spring.application.name=backend
spring.datasource.url=jdbc:postgresql://localhost:5432/MedHub
spring.datasource.username=postgres
spring.datasource.password=SarMos@43

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true